### ISSUE TITLE
Stopped working in kitty 0.17.0

### ISSUE THREAD

**Issue by orthodoX** [yurikhan/kitty_grab#10]
I've updated `kitty` today to `0.17.0` on macOS and `kitty_grab` stopped working. I've also updated some configs  `kitty.conf` meanwhile, so not sure is it the update itself or something else. How can I properly debug this extension?

**Comment by orthodoX** [comment]
@yurikhan I've downgraded kitty to 0.16.0 and grab is working again, so it's definitely related to the new version of kitty.

**Comment by yurikhan** [comment]
I will look into it. Not right now, maybe on the weekend.

**Comment by yurikhan** [comment]
Should be fixed by c3f127d. If not, please reopen with a reproduction recipe.

**Comment by orthodoX** [comment]
Works, thanks! ❤️
