### ISSUE TITLE
Vim style movement

### ISSUE THREAD

**Issue by IndianBoy42** [yurikhan/kitty_grab#15]
Is it possible through configuration to make the movement vim style (for example like alacritty's ctrl+shift+space)

**Comment by yurikhan** [comment]
I do not know what Ctrl+Shift+Space does in Alacritty.

I do know vim has a whole chapter in its manual called motion.txt and spanning almost one and a half thousand lines, and that not including search commands.

I know some vim commands use a prefix key such as `g`. Kitty has a `key1>key2` syntax for key sequences, but I have not tested if they work in kitty_grab. Likely not yet.

I also know most vim commands can be prefixed with numbers, and I am certain Kitty does not have a syntax for that.

Lastly, I know some people have had success setting up vim or neovim as a screen grabber / scrollback browser for Kitty, see [here](https://github.com/kovidgoyal/kitty/issues/719) and [there](https://github.com/kovidgoyal/kitty/issues/2327).

**Comment by IndianBoy42** [comment]
Well you don't have to support all of vims motions of course. Alacrittys vi mode just supports the basics

hjkl instead of arrows

wbe for moving by word

v to start selecting, V to select whole lines at a time

y to copy what has been selected

/? to search fwd/bwd

That's just about what alacritty supports

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by yurikhan** [comment]
> hjkl instead of arrows

Possible.

> wbe for moving by word

Two of three possible, because kitty_grab does not implement two different ways to move forward by words.

> v to start selecting, V to select whole lines at a time

Modal selection is not currently implemented. I might accept a patch.

> y to copy what has been selected

Possible.

> /? to search fwd/bwd

Search is not yet implemented. I have a wishlist item (#5) for search but it’s about emacs-style isearch rather than vim-style regexp search.

(Offtopic: When replying via mail client, please delete anything that should not go into a comment. This includes your mail signature and bottom-quoting.)

Also, have you read the sample config? It should have told you everything that is possible.

**Comment by storopoli** [comment]
Any new on this?

The most important stuff would be:

> `v` to start selecting, `V` to select whole lines at a time

**Comment by yurikhan** [comment]
Are you volunteering to implement that?

**Comment by yurikhan** [comment]
Then I have no news for you, sorry.

**Comment by tigerjack** [comment]
Hey @IndianBoy42 , there's part of this is already implemented on kitty. For example, `Ctrl+G` let you go around the output of the last command (it uses `less` in the background I think). Some people (including me) are also using `nvim` as a scrollback pager to be able to select text. [This](https://github.com/tigerjack/dotfiles/blob/d333df8e4e1d2660f626c9bc65c75fd0719a2576/.config/kitty/override.conf#L8) is my configuration for example.
