### ISSUE TITLE
Unable to map ctrl+d?

### ISSUE THREAD

**Issue by alkim0** [yurikhan/kitty_grab#23]
I'm trying to map:
```
map Ctrl+d      move page down
```
in `grab.conf`, but it seems to not be working.

All other shortcuts, such as:
```
map Ctrl+f      move page down
```
works fine. Just not ctrl+d.

**Comment by yurikhan** [comment]
Interesting. Can you dig down to see where it goes wrong?

**Comment by yurikhan** [comment]
Hm. Logging key events at the start of `GrabHandler.on_key_event` shows this:

```
EventType.PRESS 0 RIGHT_CONTROL
EventType.RELEASE 4 d
EventType.RELEASE 4 RIGHT_CONTROL
EventType.PRESS 0 ESCAPE
EventType.PRESS 0 RIGHT_CONTROL
EventType.PRESS 4 f
EventType.RELEASE 4 f
EventType.RELEASE 4 RIGHT_CONTROL
```

i.e. for Ctrl+d, we don’t receive the press event. We will need to dive into the Kitty code, and/or file an issue against kitty.

**Comment by alkim0** [comment]
I tried running kitty with `--debug-input`, and that seems to pass the event to the application, but I'll take a closer look later.

**Comment by alkim0** [comment]
I've looked into this, and it seems this is done by design. In kitty/tui/loop.py, ctrl+d calls `on_eot` and returns and ctrl+c calls `on_interrupt` and returns. All other key sequences go to `on_key_event`.

Since vim users expect ctrl+d and ctrl+u to work as page down/up, could I ask that the above pull request be incorporated to match feature parity?

**Comment by yurikhan** [comment]
Ugh. Let’s see if we can get the design improved first.
