### ISSUE TITLE
[feat] change (dim) background color

### ISSUE THREAD

**Issue by k4lizen** [yurikhan/kitty_grab#30]
I would like some indication that I am currently in grab mode. I have the top window bar disabled, so changing the background for example would be a nice way to do that.

I only see
```
#: Colors {{{

# selection_foreground #FFFFFF
# selection_background #5294E2

#: Colors for selected text while grabbing.

#: }}}
```
the selection color in the example config.

**Comment by yurikhan** [comment]
I’m not very keen about changing the background, for reasons:

* The grabber does not know colors. It gets the text of the buffer marked up with ANSI escape sequences and lets the terminal interpret and display it.
* To modify the background in a pleasant way, the grabber would have to interpret the 24-bit color escape sequences, and to know values of the 256-color palette.
* Setting all the backgrounds to a single preconfigured color is out of the question as it would make every full-screen terminal application look weird in grab mode.

I think I could change the cursor color to something configurable separately from the Kitty `cursor` option. Would that solve your case?

**Comment by k4lizen** [comment]
Sure! That would be great

**Comment by yurikhan** [comment]
Done.

The default cursor color for grabbing is a shade of purple that should:

* yield good contrast on either black or white overall background;
* not be semantically loaded like red (error) or orange (warning); and
* be sufficiently distinct from (1) the default grabbing selection background color (blue), (2) the default Kitty cursor color (light gray), and (3) my preferred cursor color (green).
